/*
    Copyright 2022, 2024 Olli Helin
    This file is part of Virtuaalivaluuttaverotuslaskin, a free software released under the terms of the
    GNU General Public License v3: http://www.gnu.org/licenses/gpl-3.0.en.html
*/

export default {
    '00'        : '00 Token',
    'AAVE'      : 'Aave',
    'ADA'       : 'Cardano',
    'AMP'       : 'Amp',
    'ANKR'      : 'Ankr',
    'ATOM'      : 'Cosmos',
    'BOBA'      : 'Boba Network',
    'BTC'       : 'Bitcoin',
    'CGLD'      : 'Celo',
    'COCAINU'   : 'Cocainu',
    'DNT'       : 'district0x',
    'DOT'       : 'Polkadot',
    'ETH'       : 'Ethereum',
    'GRT'       : 'The Graph',
    'HIDEME'    : 'HideMe',
    'ICP'       : 'Internet Computer',
    'JAPAN'     : 'Japan Coin',
    'JASMY'     : 'Jasmy',
    'KITTENWIF' : 'KittenWifHat',
    'KNC'       : 'Kyber Network Crystal',
    'LINK'      : 'Chainlink',
    'LTC'       : 'Litecoin',
    'MATIC'     : 'Polygon',
    'NEONPEPE'  : 'NEON PEPE',
    'ORN'       : 'Orion Protocol',
    'OXT'       : 'Orchid',
    'REP'       : 'Augur',
    'RLC'       : 'iExec RLC',
    'SOL'       : 'Solana',
    'STORJ'     : 'Storj',
    'TRU'       : 'TrueFi',
    'TRX'       : 'TRON',
    'UMA'       : 'UMA',
    'VET'       : 'VeChain',
    'XLM'       : 'Stellar Lumens',
    'XRP'       : 'Ripple',
    'XTZ'       : 'Tezos',
    'ZEC'       : 'Zcash',
    'ZRX'       : '0x',
}
